# Generated by Django 4.0.2 on 2022-02-24 11:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to='Events', verbose_name='Image'),
        ),
    ]
