# Generated by Django 3.1.7 on 2022-03-07 00:07

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20220302_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='target',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='volunteers',
            field=models.ManyToManyField(related_name='myevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(default=events.models.in_fourteen_days),
        ),
    ]
