# Generated by Django 3.1.7 on 2022-03-07 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20220307_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='interests',
            field=models.ManyToManyField(related_name='myinterests', to=settings.AUTH_USER_MODEL),
        ),
    ]
