# Generated by Django 4.0.2 on 2022-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avata',
            field=models.ImageField(default=None, upload_to='comments', verbose_name='Imag'),
        ),
        migrations.AddField(
            model_name='comments',
            name='first',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
