# Generated by Django 3.1.7 on 2022-03-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_events_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.ImageField(default='profile_images/default-pic.jpeg', upload_to='profile_images', verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='comments',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comments',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.events'),
        ),
        migrations.AddField(
            model_name='comments',
            name='userName',
            field=models.CharField(default=None, max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
