# Generated by Django 4.0.2 on 2022-02-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_comments_avata_comments_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='avata',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='first',
        ),
    ]
