# Generated by Django 3.1.7 on 2022-03-03 19:41

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('H', 'home'), ('W', 'worker'), ('S', 'shop')], default='P', max_length=1)),
                ('type', models.CharField(choices=[('H', 'home'), ('W', 'worker'), ('S', 'shop')], default='H', max_length=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^01[0125][0-9]{8}$', 'Egyptian phone number is required')], verbose_name='phone')),
                ('paper_q', models.IntegerField()),
                ('plastic_q', models.IntegerField()),
                ('metal_q', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
