# Generated by Django 3.1.7 on 2022-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'approved'), ('S', 'shipping'), ('D', 'delivered')], default='P', max_length=1),
        ),
    ]
