# Generated by Django 4.0.2 on 2022-02-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='metal',
            new_name='metal_quantity',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='paper',
            new_name='paper_quantity',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='plastic',
            new_name='plastic_quantity',
        ),
    ]
