# Generated by Django 3.1.7 on 2022-03-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220311_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-order_date',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
