# Generated by Django 4.0.2 on 2022-02-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_metal_orders_metal_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='metal_quantity',
            new_name='metal_q',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='paper_quantity',
            new_name='paper_q',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='plastic_quantity',
            new_name='plastic_q',
        ),
    ]
