# Generated by Django 4.0.2 on 2022-02-27 23:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_metal_quantity_orders_metal_q_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='metal_q',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paper_q',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='plastic_q',
            field=models.IntegerField(),
        ),
    ]
