# Generated by Django 4.0.2 on 2022-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_metal_quantity_orders_metal_q_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='metal_q',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paper_q',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='plastic_q',
            field=models.IntegerField(),
        ),

    ]
