# Generated by Django 4.0.2 on 2022-03-01 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_location_alter_orders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
