# Generated by Django 4.0.2 on 2022-02-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='cdcity',
            new_name='city',
        ),
    ]
