# Generated by Django 4.0.2 on 2022-02-24 00:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userlocation_latitude_userlocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
