# Generated by Django 3.1.7 on 2022-03-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('paper_price', models.FloatField(default=0)),
                ('plastic_price', models.FloatField(default=0)),
                ('metal_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('annual_production', models.FloatField(default=0)),
                ('annual_consumption', models.FloatField(default=0)),
                ('annual_recycling', models.FloatField(default=0)),
            ],
        ),
    ]
