# Generated by Django 3.1.7 on 2022-03-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_rate_and_price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material_price',
            old_name='metal_price',
            new_name='home_price',
        ),
        migrations.RenameField(
            model_name='material_price',
            old_name='category',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='material_price',
            old_name='paper_price',
            new_name='shop_price',
        ),
        migrations.RenameField(
            model_name='material_price',
            old_name='plastic_price',
            new_name='workers_price',
        ),
    ]
