# Generated by Django 3.1.7 on 2022-03-14 10:43

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None)),
                ('quantities', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=None)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('being_delivered', models.BooleanField(default=True)),
                ('received', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Products order',
                'verbose_name_plural': 'Products order ',
                'db_table': 'orderproduct',
                'ordering': ('-order_date',),
            },
        ),
    ]
