# Generated by Django 4.0.2 on 2022-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_product', '0002_alter_orderproduct_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
